name: dk_mart_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  icons_plus: ^5.0.0
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.2
  flutter_dotenv: ^5.2.1
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/onboarding/
    - assets/images/Banners/
    - assets/images/Custom_Icons/
    - assets/sampleProducts/
    - assets/sampleProducts/casualComfort/
    - assets/sampleProducts/runningMaster/
    - assets/sampleProducts/sneakerPro/

    - .env
  fonts:
    - family: Staatliches
      fonts:
        - asset: assets/fonts/Staatliches-Regular.ttf

# Icon Generator   //Dont  Remove this
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png" # Updated to use SVG logo
  min_sdk_android: 21 #

# Native Splash Screen  //Dont  Remove this
flutter_native_splash:
  color: "#ffffff" # This is already white
  image: assets/images/logo.png # Updated to use SVG logo
